### tides by default location
# 42.7101,-70.7886
http://localhost:8080/api/tides/by-location

### tides by location
http://localhost:8080/api/tides/by-location/42.7101,-70.7886

### tides by default station
# 8441241
http://localhost:8080/api/tides/by-station

### tides by station
http://localhost:8080/api/tides/by-station/8441241

### stations
http://localhost:8080/api/stations

### station by id
http://localhost:8080/api/stations/8441241
