openapi: 3.1.0
info:
  title: tide-catcher-next-backend
  description: Backend API serving the Tide Catcher Next frontend
  version: '1.1'
servers:
  - url: 'http://localhost:8080'
    description: Development
  - url: 'https://tide-catcher.justinwhite.net'
    description: Production
  - url: 'https://tide-catcher-next.vercel.app'
    description: Alternate
paths:
  /api/station/{station}:
    get:
      description: metadata for given station
      parameters:
        - in: path
          name: station
          schema:
            type: string
            example: "8441241"
          required: false
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationsResponse"

  /api/station/location/{location}:
    get:
      description: closest single station to the given location, if any, within 10-160 miles
      parameters:
        - in: path
          name: location
          schema:
            type: string
            example: "42.71014,-70.78861"
          required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationsResponse"

  /api/stations/location/{location}:
    get:
      description: closest stations to the given location, if any, within 10-160 miles
      parameters:
        - in: path
          name: location
          schema:
            type: string
            example: "42.71014,-70.78861"
          required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationsResponse"

  /api/stations:
    get:
      description: list of all cached stations
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationsResponse"

  /api/tides/station/{id}:
    get:
      description: list of next tides for the given station
      parameters:
        - in: path
          name: station
          schema:
            type: string
            example: "8441241"
          required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TidesResponse"

  /api/tides/location/{location}:
    get:
      description: list of next tides for the closest station
      parameters:
        - in: path
          name: location
          schema:
            type: string
            example: "42.71014,-70.78861"
          required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TidesResponse"

components:
  schemas:
    Station:
      description: Station entity
      type: object
      properties:
        id:
          type: string
          description: Unique ID of the station
        lat:
          type: number
          format: float
          description: Latitude of the station
        lon:
          type: number
          format: float
          description: Longitude of the station
        name:
          type: string
          description: Name of the station
        eTimesName:
          type: string
          description: Name used by the NOAA Tide Predictions website
        tzOffset:
          type: number
          description: timezone offset in hours from UTC of the station
      example:
        {
          "id": "8441241",
          "location": "42.71014,-70.78861",
          "name": "Plum Island South",
          "eTidesName": "Plum Island South",
          tzOffset: -5
        }

    StationsResponse:
      description: List of Stations
      type: object
      properties:
        status:
          type: string
        station_count:
          type: integer
        stations:
          type: array
          items:
            $ref: "#/components/schemas/Station"
      example:
        {
          "reqLocation": "42.71014,-70.78861",
          "station_count": 1,
          "stations": [
            {
              "id": "8441241",
              "location": "42.71014,-70.78861",
              "name": "Plum Island South",
              "eTidesName": "Plum Island Sound (south end)",
              "tzOffset": -5
            }
          ]
        }

    Tide:
      description: Tide entity
      type: object
      properties:
        date:
          type: string
          description: Date of the tide
        day:
          type: string
          description: Day of the week
        height:
          type: number
          format: float
          description: Height of the tide
        iso-date:
          type: string
          format: date-time
          description: ISO formatted date and time of the tide
        prior:
          type: string
          description: Indicates if the tide is "prior" or "next"
        time:
          type: string
          description: Time of the tide
        type:
          type: string
          description: Type of tide (e.g., "Low", "High")
      example:
        {
          "source_date": "2025-10-02 01:59",
          "date": "10/02",
          "day": "Thu",
          "height": 0.369,
          "iso_date": "2025-10-02T05:59:00.000Z",
          "time": "01:59",
          "type": "low"
        }

    TidesResponse:
      description: A set of Tides from a station
      type: object
      properties:
        reqLat:
          type: number
          format: float
          description: Requested latitude
        reqLon:
          type: number
          format: float
          description: Requested longitude
        reqTimestamp:
          type: string
          format: date-time
          description: Requested timestamp
        respLat:
          type: number
          format: float
          description: Responded latitude
        respLon:
          type: number
          format: float
          description: Responded longitude
        station:
          type: string
          description: Name of the tide station
        stationTz:
          type: string
          description: Timezone of the station
        status:
          type: integer
          description: HTTP status code
        tides:
          type: array
          items:
            $ref: "#/components/schemas/Tide"
      example:
        {
          "reqLocation": "42.71014,-70.78861",
          "reqTimestamp": "2025-10-01T16:20:58.872Z",
          "stationLocation": "42.71014,-70.78861",
          "stationId": "8441241",
          "stationName": "Plum Island South",
          "stationTzOffset": -5,
          "tides": [
            {
              "source_date": "2025-10-02 01:59",
              "date": "10/02",
              "day": "Thu",
              "height": 0.369,
              "iso_date": "2025-10-02T05:59:00.000Z",
              "time": "01:59",
              "type": "low"
            }
          ]
        }
