openapi: 3.0.0

info:
  title: tide-catcher-next-backend
  description: Backend API serving the Tide Catcher Next frontend
  version: "1.1"

servers:
  - url: "http://localhost:3000"
    description: Development
  - url: "https://tide-catcher.justinwhite.net"
    description: Production
  - url: "https://tide-catcher-next.vercel.app"
    description: Alternate

paths:
  /api/stations:
    get:
      description: metadata for the default station
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationsResponse"

  /api/stations/{id}:
    get:
      description: metadata for given station
      parameters:
        - $ref: "#/components/parameters/stationId"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationsResponse"

  /api/stations/all:
    get:
      description: list of all cached stations
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationsResponse"

  /api/stations/location:
    get:
      description: list of closest stations to the default location, if any, within 10-160 miles
      parameters:
        - $ref: "#/components/parameters/stationCount"
        - $ref: "#/components/parameters/stationRange"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationsResponse"

  /api/stations/location/{loc}:
    get:
      description: list of closest stations to the given location, if any, within 10-160 miles
      parameters:
        - $ref: "#/components/parameters/location"
        - $ref: "#/components/parameters/stationCount"
        - $ref: "#/components/parameters/stationRange"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationsResponse"

  /api/tides/location:
    get:
      description: list of next tides for the closest station to the default location
      parameters:
        - $ref: "#/components/parameters/tzOffsetHeader"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TidesResponse"

  /api/tides/location/{loc}:
    get:
      description: list of next tides for the closest station to the given location
      parameters:
        - $ref: "#/components/parameters/location"
        - $ref: "#/components/parameters/tzOffsetHeader"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TidesResponse"

  /api/tides/station:
    get:
      description: list of next tides for the default station
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TidesResponse"

  /api/tides/station/{id}:
    get:
      description: list of next tides for the given station
      parameters:
        - $ref: "#/components/parameters/stationId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TidesResponse"

components:
  parameters:
    stationId:
      description: "A Station ID: string of 7 digits, or 3 letters followed by 4 digits"
      in: path
      name: id
      required: true
      schema:
        type: string
      example: "8441241"
    location:
      description: "A Location: string of 2 comma-separated numbers"
      in: path
      name: loc
      required: true
      schema:
        type: string
      example: "42.710,-70.788"
    stationCount:
      description: "Limit the number of stations returned"
      in: query
      name: count
      required: false
      schema:
        type: number
        default: 10
    stationRange:
      description: "Limit the number of stations returned"
      in: query
      name: range
      required: false
      schema:
        type: number
        default: 10
    tzOffsetHeader:
      description: "A Timezone Offset, in minutes, as a string"
      in: header
      name: "X-Tidecatcher-Tz-Offset"
      schema:
        type: string

  schemas:
    Status:
      description: The status of the request
      type: object
      properties:
        code:
          type: string
        msg:
          type: string
          default: ""
      example:
        status: { code: 200, msg: "OK" }

    Location:
      description: Structured latitude and longitude
      type: object
      properties:
        lat:
          type: number
          format: float
          description: Latitude
        lon:
          type: number
          format: float
          description: Longitude
      example:
        "location": { "lat": 42.710, "lon": -70.788 }

    Station:
      description: Station entity
      type: object
      properties:
        id:
          type: string
          description: Unique ID of the station
        location:
          type: object
          items:
            $ref: "#/components/schemas/Location"
        name:
          type: string
          description: Name of the station
        eTimesName:
          type: string
          description: Name used by the NOAA Tide Predictions website
        tzOffset:
          type: number
          description: timezone offset in hours from UTC of the station
      example:
        {
          "id": "8441241",
          "location": { "lat": 42.710, "lon": -70.788 },
          "name": "Plum Island South",
          "eTidesName": "Plum Island South",
          "tzOffset": -5,
        }

    StationsResponse:
      description: List of Stations
      type: object
      properties:
        status:
          type: object
          items:
            $ref: "#/components/schemas/Status"
        reqLocation:
          type: object
          items:
            $ref: "#/components/schemas/Location"
        count:
          type: integer
        stations:
          type: array
          items:
            $ref: "#/components/schemas/Station"
      example:
        {
          "status": { code: "OK", message: "" },
          "reqLocation": { "lat": 42.710, "lon": -70.788 },
          "count": 1,
          "stations":
            [
              {
                "id": "8441241",
                "location": { "lat": 42.710, "lon": -70.788 },
                "name": "Plum Island South",
                "eTidesName": "Plum Island South",
                "tzOffset": -5,
              },
            ],
        }

    Tide:
      description: Tide entity
      type: object
      properties:
        sourceDate:
          type: string
          description: Date exactly from NOAA API
        isoDate:
          type: string
          format: date-time
          description: ISO formatted date and time of the tide
        localDate:
          type: string
          format: date-time
          description: ISO formatted date and time of the tide, possibly in a different timezone as iso-date
        type:
          type: string
          description: Type of tide (e.g., "Low", "High")
        time:
          type: string
          description: Time of the tide
        day:
          type: string
          description: day of the week of the tide
        date:
          type: string
          description: <month>:<day> of the time
        height:
          type: number
          format: float
          description: Height of the tide
      example:
        {
          "sourceDate": "2025-10-15 13:16",
          "isoDate": "2025-10-15T17:16:00Z",
          "localDate": "2025-10-15T13:16:00-04:00",
          "type": "low",
          "time": "13:16",
          "day": "Wed",
          "date": "10/15",
          "height": 0.311,
        }

    TidesResponse:
      description: A set of Tides from a station
      type: object
      properties:
        status:
          type: object
          items:
            $ref: "#/components/schemas/Status"
        reqLocation:
          type: object
          items:
            $ref: "#/components/schemas/Location"
        station:
          type: object
          items:
            $ref: "#/components/schemas/Station"
        tides:
          type: array
          items:
            $ref: "#/components/schemas/Tide"
      example:
        {
          "status": { code: "OK", message: "" },
          "reqLocation": { "lat": 42.710, "lon": -70.788 },
          "station":
            {
              "id": "8441241",
              "location": { "lat": 42.710, "lon": -70.788 },
              "name": "Plum Island South",
              "eTidesName": "Plum Island Sound (south end)",
              "tzOffset": -5,
            },
          "tides":
            [
              {
                "sourceDate": "2025-10-15 13:16",
                "isoDate": "2025-10-15T17:16:00Z",
                "localDate": "2025-10-15T13:16:00-04:00",
                "type": "low",
                "time": "13:16",
                "day": "Wed",
                "date": "10/15",
                "height": 0.311,
              },
            ],
        }
