openapi: 3.1.0
info:
  title: tide-catcher-backend
  description: tide-catcher-backend
  version: 1.0.0
servers:
  - url: 'http://localhost:5000'
    description: Development
  - url: 'https://tide-catcher.appspot.com'
    description: Production
paths:
  /json/tides/by-location/{location}:
    get:
      description: list of next tides for the closest station
      parameters:
        - in: path
          name: location
          schema:
            type: string
            example: "42.665,-70.9119"
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TidesResponse"

  /json/tides/by-station/{station}:
    get:
      description: list of next tides for the given station
      parameters:
        - in: path
          name: station
          schema:
            type: string
            example: "NOAA:8440452"
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TidesResponse"

  /json/stations:
    get:
      description: list of all cached stations
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Stations"

  /json/stations/refresh:
    get:
      description: update stations cache, return list of newly cached stations
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationsResponse"

  /json/station/by-id/{station}:
    get:
      description: metadata for given station
      parameters:
        - in: path
          name: station
          schema:
            type: string
            example: "NOAA:8441241"
          required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationResponse"

  /json/station/by-nearest/{location}:
    get:
      description: closest station to the given location
      parameters:
        - in: path
          name: location
          schema:
            type: string
            example: "42.665,-70.9119"
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationResponse"

components:
  schemas:
    Tide:
      description: Tide entity
      type: object
      properties:
        date:
          type: string
          description: Date of the tide
        day:
          type: string
          description: Day of the week
        height:
          type: number
          format: float
          description: Height of the tide
        iso-date:
          type: string
          format: date-time
          description: ISO formatted date and time of the tide
        prior:
          type: string
          description: Indicates if the tide is "prior" or "next"
        time:
          type: string
          description: Time of the tide
        type:
          type: string
          description: Type of tide (e.g., "Low", "High")
      example:
        {
          "date": "06-11",
          "day": "Wed",
          "height": 0.483,
          "iso-date": "2025-06-11T18:31:50-04:00",
          "prior": "prior",
          "time": "18:31",
          "type": "Low"
        }

    TidesResponse:
      description: A set of Tides from a station
      type: object
      properties:
        req_lat:
          type: number
          format: float
          description: Requested latitude
        req_lon:
          type: number
          format: float
          description: Requested longitude
        req_timestamp:
          type: string
          format: date-time
          description: Requested timestamp
        resp_lat:
          type: number
          format: float
          description: Responded latitude
        resp_lon:
          type: number
          format: float
          description: Responded longitude
        station:
          type: string
          description: Name of the tide station
        station_tz:
          type: string
          description: Timezone of the station
        status:
          type: integer
          description: HTTP status code
        tides:
          type: array
          items:
            $ref: "#/components/schemas/Tide"
      example:
        {
          "req_lat": 42.6724,
          "req_lon": -70.9443,
          "req_timestamp": "Wed, 11 Jun 2025 10:08:36 EDT",
          "resp_lat": 42.7101,
          "resp_lon": -70.7886,
          "station": "Plum Island Sound (south end), Massachusetts",
          "station_tz": "America/New_York",
          "status": 200,
          "tides": [
            {
              "date": "06-11",
              "day": "Wed",
              "height": 0.483,
              "iso-date": "2025-06-11T18:31:50-04:00",
              "prior": "prior",
              "time": "18:31",
              "type": "Low"
            }
          ]
        }

    Station:
      description: Station entity
      type: object
      properties:
        id:
          type: string
          description: Unique ID of the station
        lat:
          type: number
          format: float
          description: Latitude of the station
        lon:
          type: number
          format: float
          description: Longitude of the station
        name:
          type: string
          description: Name of the station
        noaa:
          type: boolean
          description: Indicates if the station is a NOAA station
        org:
          type: string
          description: Organization managing the station
        org_id:
          type: string
          description: Organization-specific ID of the station
      example:
        {
          "id": "NOAA:8441241",
          "lat": 42.7101,
          "lon": -70.7886,
          "name": "Plum Island Sound (south end), Massachusetts",
          "noaa": true,
          "org": "NOAA",
          "org_id": "8441241"
        }

    StationResponse:
      description: One Station
      type: object
      properties:
        status:
          type: string
        station:
          $ref: "#/components/schemas/Station"
      example:
        {
          "status": "OK",
          "station": [
            {
              "id": "NOAA:8441241",
              "lat": 42.7101,
              "lon": -70.7886,
              "name": "Plum Island Sound (south end), Massachusetts",
              "noaa": true,
              "org": "NOAA",
              "org_id": "8441241"
            }
          ]
        }

    StationsResponse:
      description: List of Stations
      type: object
      properties:
        status:
          type: string
        station_count:
          type: integer
        stations:
          type: array
          items:
            $ref: "#/components/schemas/Station"
      example:
        {
          "status": "OK",
          "station_count": 1,
          "stations": [
            {
              "id": "NOAA:8441241",
              "lat": 42.7101,
              "lon": -70.7886,
              "name": "Plum Island Sound (south end), Massachusetts",
              "noaa": true,
              "org": "NOAA",
              "org_id": "8441241"
            }
          ]
        }
