import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <title>Tide Catcher</title>

          <meta charSet="UTF-8"/>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>

          <link rel="apple-touch-icon" sizes="57x57" href="/static/icons/apple-icon-57x57.png"/>
          <link rel="apple-touch-icon" sizes="60x60" href="/static/icons/apple-icon-60x60.png"/>
          <link rel="apple-touch-icon" sizes="72x72" href="/static/icons/apple-icon-72x72.png"/>
          <link rel="apple-touch-icon" sizes="76x76" href="/static/icons/apple-icon-76x76.png"/>
          <link rel="apple-touch-icon" sizes="114x114" href="/static/icons/apple-icon-114x114.png"/>
          <link rel="apple-touch-icon" sizes="120x120" href="/static/icons/apple-icon-120x120.png"/>
          <link rel="apple-touch-icon" sizes="144x144" href="/static/icons/apple-icon-144x144.png"/>
          <link rel="apple-touch-icon" sizes="152x152" href="/static/icons/apple-icon-152x152.png"/>
          <link rel="apple-touch-icon" sizes="180x180" href="/static/icons/apple-icon-180x180.png"/>

          <link rel="icon" type="image/png" sizes="192x192" href="/static/icons/android-icon-192x192.png"/>
          <link rel="icon" type="image/png" sizes="32x32" href="/static/icons/favicon-32x32.png"/>
          <link rel="icon" type="image/png" sizes="96x96" href="/static/icons/favicon-96x96.png"/>
          <link rel="icon" type="image/png" sizes="16x16" href="/static/icons/favicon-16x16.png"/>

          <link rel="manifest" href="/static/manifest/manifest.json"/>
          <meta name="msapplication-TileColor" content="#ffffff"/>
          <meta name="msapplication-TileImage" content="/static/icons/ms-icon-144x144.png"/>
          <meta name="theme-color" content="#ffffff"/>

          <link rel="stylesheet" type="text/css" href="/static/css/main.css" media="screen, handheld"/>

          <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js" defer></script>-->
          <script src="/static/js/contrib/jquery-3.1.0.min.js" defer></script>
          <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js" defer></script>-->
          <script src="/static/js/contrib/underscore-1.8.3-min.js" defer></script>
          <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.3.3/backbone-min.js" defer></script>-->
          <script src="/static/js/contrib/backbone-1.3.3-min.js" defer></script>
          <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/2.2.1/mustache.min.js"defer ></script>-->
          <script src="/static/js/contrib/mustache-2.2.1.min.js" defer></script>

          <script src="/static/js/index.js" defer></script>

      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
