
### station by id
{{host}}/api/station/{{station}}

### station from bad id
{{host}}/api/station/{{badStation}}

### station by default id: 8441241
{{host}}/api/station

### single nearest station within 10 miles
{{host}}/api/station/location/{{location}}

### location that should have no stations in range
{{host}}/api/station/location/{{emptyLocation}}

### single nearest station within 10 miles of default location: 42.710,-70.788
{{host}}/api/station/location

### multiple nearest stations within 10 miles
{{host}}/api/stations/location/{{location}}

### stations by default location: 42.710,-70.788
{{host}}/api/stations/location

### bad location
{{host}}/api/stations/location/{{badLocation}}

### all stations
{{host}}/api/stations

//### all stations refresh
//{{host}}/api/stations/refresh

### tides by id
{{host}}/api/tides/station/{{station}}

### tides by default id: 8441241
{{host}}/api/tides/station

### tides by location
{{host}}/api/tides/location/{{location}}

### tides by default location: 42.710,-70.788
{{host}}/api/tides/location
