
### station by default id: 8441241
{{host}}/api/stations

### station by id
{{host}}/api/stations/{{station}}

### station from bad id
{{host}}/api/stations/{{badStation}}

### single nearest station within 10 miles of default location: 42.710,-70.788
{{host}}/api/stations/location

### 10 nearest station within 10 miles of default location: 42.710,-70.788
{{host}}/api/stations/location?count=10

### single nearest station within 10 miles
{{host}}/api/stations/location/{{location}}

### 10 nearest stations within 10 miles (only 7)
{{host}}/api/stations/location/{{location}}?count=10

### 10 nearest stations within 1 miles (only 1)
{{host}}/api/stations/location/{{location}}?count=10&range=1

### 200 nearest stations within 100 miles (should be ~167)
{{host}}/api/stations/location/{{location}}?count=200&range=100

### location that should have no stations in range
{{host}}/api/stations/location/{{emptyLocation}}

### intentionally requesting empty list
{{host}}/api/stations/location?count=0

### bad location
{{host}}/api/stations/location/{{badLocation}}

### all stations
{{host}}/api/stations/all

### tides by id
{{host}}/api/tides/station/{{station}}

### tides by default id: 8441241
{{host}}/api/tides/station

### tides by location
{{host}}/api/tides/location/{{location}}

### tides by default location: 42.710,-70.788
{{host}}/api/tides/location
